language: groovy
jdk:
- openjdk6
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: OdeMwbsdRQzq3hIpSOqeFM5fL5W0ecJ/6kmVzTLMOn6fVyKdbnIx7wp7ICd+OSg38mKCWI658KgPns5vxAivCiQZznA2wdSMIVg2vINDaHQFU2uPSs8nJle5ndzeSRax2ja2APPVCsRcR73seYCRIBR2fV/AcBTHkjzODXjU1zA=
  - secure: XsHL1m+IHgj+p/8XuTHZ/6iVrNs+hDtdEbYAtjtClDtCnyxgw/YpENe6eexfP4leEv+1Ani37reJQWoOojVC59SbhGEByI8KiIhMygc/oGcQcxasSG9MBo2DEJ4PtGPrNvAcZnX0LYlDeBHpYOe8s9YXqN/szGaFEk/e/H+A6Yo=
  - secure: JaFy58AdmU5xBKcUhdcDAQpG9cKbSsNjuVIN/JVuRKUiF+ybVpUEIwSMrsD4twi60zmMOrTevWuDc0u+euxfO0PV9z1/c/KeMLqJqY/vYgRaGZqo+hbL/gNjfoJNRhpxCpQyx1eL0Z06VxFmF6lU7zS/eeJ3fn8wrKtUl5gGD0Q=
